### PR TITLE
Add attributes settings

### PR DESCRIPTION
**Pull request by nlemoine**

### CODE REVIEW

**Comment by frozzare** [comment]
awesome 👍

**Comment by nlemoine** [comment]
Maybe default value for `step` attribute should be `any`?

I used the default number property (without any settings, hence this PR) for latitude/longitude fields and the HTML5 validation raised an error on a float when default input is:
```html
<input type="number" step min max />
```
See: https://jsbin.com/gutaqa/4/edit?html,output

**Comment by frozzare** [comment]
If that's is okay with HTML5 standard then I'm okay with changing the default value.

**Comment by nlemoine** [comment]
The `any` string seems to be a [valid attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) (search for `step`).

**Comment by frozzare** [comment]
@nlemoine can you make a pr to master with this change? I'm trying to get 3.2 done as soon as possible :)

**Comment by nlemoine** [comment]
Done.

**Comment by frozzare** [comment]
thanks 👍

**Pull request merged**
